# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-east-1"
  profile = "yulyan"

  assume_role {
    session_name = "session-yulyan"
    role_arn = "arn:aws:iam::468617488226:role/yulyan-apply" 
  }
}
